### ISSUE TITLE
Missing Icons, Server Panel Color Mismatch

### ISSUE THREAD

**Issue by Cidtaru** [Flonneon/Discord-Theme-Kancolle-Shiratsuyu-Class#5]
![example](https://user-images.githubusercontent.com/29290792/26953538-ea7c5144-4c78-11e7-9085-71bb0902fd96.jpg)
Hello,

Sorry if the image is a bit unclear but it seems like a recent update has messed with some of the icons and the background color of the server panel. 

The User Settings Gear beside the Username at the bottom has also turned into an X, and the icons beside the text and voice channels have also turned into generic x's.

**Comment by Flonneon** [comment]
i noticed it and working on it,gonna be done tomorrow or latest at saturday

**Comment by Flonneon** [comment]
while merging files github got conflicted,dunno why but github reverted all changes and my work went rip.
gonna redo it in a week or two maybe

**Comment by Cidtaru** [comment]
I still have the old .css file, would that help?

**Comment by Flonneon** [comment]
i have the old css,but not the new one which got reverted : x
for now i just fixed the chat...everything else is gonna be redone later
