### ISSUE TITLE
theme doesn't show up in themes section.

### ISSUE THREAD

**Issue by dadahaaaaaaaa** [Flonneon/Discord-Theme-Kancolle-Shiratsuyu-Class#9]
i've popped the css in the themes folder and all that jazz, but betterdiscord doesn't seem the notice it so its not displayed in the themes section. i have cozy and dark theme on too. i might be doing something wrong, please correct me if i am. thank you.

**Comment by Flonneon** [comment]
The theme is broken atm, and gonna stay broken until i stop being lazy and redo the theme : x
